export const referralTypes = {
  FETCH_REFERRALDATA_PROCESSING: "FETCH_REFERRALDATA_PROCESSING",
  FETCH_REFERRALDATA_SUCCESS: "FETCH_REFERRALDATA_SUCCESS",
  FETCH_REFERRALDATA_FAILURE: "FETCH_REFERRALDATA_FAILURE",

  CREATE_REFERRALLINK_PROCESSING: "CREATE_REFERRALLINK_PROCESSING",
  CREATE_REFERRALLINK_SUCCESS: "CREATE_REFERRALLINK_SUCCESS",
  CREATE_REFERRALLINK_FAILURE: "CREATE_REFERRALLINK_FAILURE",

  GET_REFERRALLINK_PROCESSING: "GET_REFERRALLINK_PROCESSING",
  GET_REFERRALLINK_SUCCESS: "GET_REFERRALLINK_SUCCESS",
  GET_REFERRALLINK_FAILURE: "GET_REFERRALLINK_FAILURE",
};
